import { createHash } from "node:crypto";
import path from "node:path";

import type { ArcModelProfileKey } from "./model-profiles.ts";

export const ARC_SUBAGENT_GENERATED_MARKER = "<!-- generated by @sentiolabs/pi-arc arc-subagents -->";
export const ARC_SUBAGENT_SYNC_VERSION = "2";

export type ArcSubagentMaterializationReason =
  | "session_start"
  | "arc_models_save"
  | "manual_repair";

export type ArcSubagentScope = "user" | "project";

export type ArcSubagentWriteStatus = "written" | "unchanged" | "skipped" | "failed";

export interface ArcSubagentWriteResult {
  agent: string;
  source: string;
  target: string;
  status: ArcSubagentWriteStatus;
  reason?: string;
}

export interface ArcSubagentShadowWarning {
  agent: string;
  projectPath: string;
  userPath: string;
  generated: boolean;
  stale: boolean;
  message: string;
}

export interface ArcSubagentMaterializationResult {
  reason: ArcSubagentMaterializationReason;
  scope: ArcSubagentScope;
  targetDir: string;
  writes: ArcSubagentWriteResult[];
  shadows: ArcSubagentShadowWarning[];
}

export interface ArcSubagentTemplate {
  sourceName: string;
  targetName: string;
  profileKey: ArcModelProfileKey;
}

export interface ArcSubagentParsedSource {
  prompt: string;
  description?: string;
  tools?: string[];
}

export interface ArcSubagentRenderInput {
  targetName: string;
  sourceName: string;
  sourceMarkdown: string;
  parsedSource: ArcSubagentParsedSource;
  resolvedModel?: string;
  modelProfileKey: ArcModelProfileKey;
  modelResolutionSource: string;
  modelsConfigHash: string;
  generatedAt: string;
}

export const ARC_PI_SUBAGENTS = [
  { source: "builder", target: "arc-builder", profileKey: "builder" },
  { source: "doc-writer", target: "arc-doc-writer", profileKey: "docWriter" },
  { source: "spec-reviewer", target: "arc-spec-reviewer", profileKey: "specReviewer" },
  { source: "code-reviewer", target: "arc-code-reviewer", profileKey: "codeReviewer" },
  { source: "evaluator", target: "arc-evaluator", profileKey: "evaluator" },
  { source: "issue-manager", target: "arc-issue-manager", profileKey: "issueManager" },
] as const;

export function resolveArcSubagentDir(
  scope: ArcSubagentScope,
  cwd: string,
  homeDir: string,
  options: { legacyUserDir?: boolean } = {},
): string {
  if (scope === "project") return path.join(cwd, ".pi", "agents");
  if (options.legacyUserDir) return path.join(homeDir, ".pi", "agent", "agents");
  return path.join(homeDir, ".agents");
}

export function isGeneratedArcSubagent(markdown: string | undefined): boolean {
  return Boolean(markdown?.includes(ARC_SUBAGENT_GENERATED_MARKER));
}

export function buildArcSubagentMetadata(input: {
  sourceName: string;
  sourceSha256: string;
  modelProfileKey: string;
  modelResolutionSource: string;
  modelsConfigSha256: string;
  generatedAt: string;
}): string {
  return [
    ARC_SUBAGENT_GENERATED_MARKER,
    `<!-- sync-version: ${ARC_SUBAGENT_SYNC_VERSION} -->`,
    `<!-- source: agents/${input.sourceName}.md -->`,
    `<!-- source-sha256: ${input.sourceSha256} -->`,
    `<!-- model-profile-key: ${input.modelProfileKey} -->`,
    `<!-- model-resolution-source: ${input.modelResolutionSource} -->`,
    `<!-- models-config-sha256: ${input.modelsConfigSha256} -->`,
    `<!-- generated-at: ${input.generatedAt} -->`,
  ].join("\n");
}

function sha256Text(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

export function buildArcSubagentMarkdown(input: ArcSubagentRenderInput): string {
  const metadata = buildArcSubagentMetadata({
    sourceName: input.sourceName,
    sourceSha256: sha256Text(input.sourceMarkdown),
    modelProfileKey: input.modelProfileKey,
    modelResolutionSource: input.modelResolutionSource,
    modelsConfigSha256: input.modelsConfigHash,
    generatedAt: input.generatedAt,
  });

  const frontmatter = [
    "---",
    `name: ${input.targetName}`,
    input.parsedSource.description ? `description: ${input.parsedSource.description}` : undefined,
    input.resolvedModel ? `model: ${input.resolvedModel}` : undefined,
    input.parsedSource.tools?.length ? `tools: ${input.parsedSource.tools.join(", ")}` : undefined,
    "systemPromptMode: replace",
    "inheritProjectContext: true",
    "inheritSkills: false",
    "---",
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");

  const body = input.parsedSource.prompt;
  return `${frontmatter}\n${metadata}\n\n${body}`;
}
